services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creche
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg: